project_id = "yjzfnzmfghxchdluxfxn"

[functions.reset-password]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.health-records-write]
verify_jwt = false

[functions.health-records-read]
verify_jwt = false

[functions.health-assessment]
verify_jwt = false

[functions.self-register]
verify_jwt = false

[functions.confirm-password-reset]
verify_jwt = false

